### ISSUE TITLE
[Suggestion] Portable git for version control

### ISSUE THREAD

**Issue by Frityet** [H3VR-Modding/MeatKit#18]
Right now, for majority of people using MeatKit, they will not have git installed on their machine and so they will have absolutely 0 version control. Version control is very important, especially with the legacy of Wolfie's project being destroyed. It would be very beneficiary if a version of [portable git](https://git-scm.com/download/win) was included in the repo, along with a tool to manage versioning from inside Unity (I can program this).

**Comment by Frityet** [comment]
also, maybe issue labels?

**Comment by nrgill28** [comment]
I agree that version control and backups are very important, and I feel like everyone should be doing one or both. But this to me just seems like a "You can lead a horse to water but you can't make them drink" situation.

The options are already there and it's not difficult to use them. Those who don't now likely still won't after, and those who didn't and learned why they should have hopefully went the extra couple steps to ensure it won't happen again. For this reason I'm not interested in having a feature like this in the main MeatKit repo.

If you just want an integrated Git(Hub) client for Unity, then that also already exists: https://unity.github.com/, otherwise if that's not quite what you're after I would recommend making your tool as a package that can be imported into any MeatKit project for those who wish to use it.

**Comment by Frityet** [comment]
I agree with your points, but what I mean is having portable git in the project, along side a tool in meatkit that tracks it, like a button that says "backup project"
